[toolchain]
package_manager = "yarn"
anchor_version = "0.30.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
givefi_contract = "48mihemhp1UxYjz1UznH4fJ9FnF3AfN3XG18GasPFamU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"